openapi: 3.0.3
info:
  title: Test Task Swagger
  version: 1.0
servers:
  - url: http://localhost:80
paths:
  /subscriptions:
    post:
      tags: ["Подписки"]
      summary: Создать запись о подписке
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, price, user_id, start_at]
              properties:
                name:
                  type: string
                  example: "Yandex Plus"
                price:
                  type: integer
                  example: 400
                user_id:
                  type: string
                  example: "60601fee-2bf1-4721-ae6f-7636e79a0cba"
                start_at:
                  type: string
                  format: string
                  example: "07-2025"
      responses:
        '201':
          description: Создано
        '400':
          description: Ошибка валидации или неверный JSON
    get:
      tags: ["Подписки"]
      summary: Получить список подписок
  /subscriptions/{id}:
    get:
      tags: ["Подписки"]
      summary: Получить подписку
    put:
      tags: ["Подписки"]
      summary: Изменить запись подписки
    delete:
      tags: ["Подписки"]
      summary: Удалить запись о подписке
